version: '3.8'
services:
  nextjs:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"